#!/bin/bash -e

if [ ! -p /var/spool/nullmailer/trigger ]; then
    rm -f /var/spool/nullmailer/trigger
    mkfifo /var/spool/nullmailer/trigger
fi
chown mail:root /var/spool/nullmailer/trigger
chmod 0622 /var/spool/nullmailer/trigger

if [ "$ADMINADDR" ]; then
    echo "$ADMINADDR" > /etc/nullmailer/adminaddr
fi

if [ "$REMOTES" ]; then
    echo "$REMOTES" > /etc/nullmailer/remotes
fi

exec chpst -u mail:mail /usr/sbin/nullmailer-send 2>&1
