#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

# Is there any other script to run here?
[ -f /etc/service/php/run.initialization ] && source /etc/service/php/run.initialization

exec chpst -u fcgi-php:$(id -Gn fcgi-php | tr ' ' ':') /usr/bin/php-cgi -q -b 127.0.0.1:9000
